# Site settings
title: Portfolio - Makoto Noda
tag_text: Portfolio - Makoto Noda
description: お仕事ください

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md", "usage.md"]
sass:
  style: compressed
